version: '3'

services:
  frontend:
    build:
      context: C:\Users\simra\PycharmProjects\CloudBasedIDE\client\frontend  # Frontend context
      dockerfile: Dockerfile  # Specify Dockerfile in the frontend directory
    ports:
      - "3000:80"  # Expose port 3000 on localhost and map to port 80 in the container
    depends_on:
      - backend

  backend:
    build:
      context: C:/Users/simra/PycharmProjects/CloudBasedIDE/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cloudide
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  user_code: